
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class FlowersList extends javax.swing.JFrame {

ArrayList<Flowers>flowerslist;
String header[] = new String[]{"Flower Name","Flower Colour","Suitable For"};
DefaultTableModel dtm;
int row,col;
    
    /**
     * Creates new form FlowersList
     */
    public FlowersList() {
        initComponents();
        flowerslist = new ArrayList<>();
        dtm = new DefaultTableModel(header,0);
        jTable2.setModel(dtm);
        this.setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFlowerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFlowerColour = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCBFlowerSuit = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        ADD = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        EDIT = new javax.swing.JButton();
        SEARCH = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Flower Name : ");

        jLabel2.setText("Flower Colour :");

        jTextFlowerColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFlowerColourActionPerformed(evt);
            }
        });

        jLabel3.setText("Suitable For :");

        jCBFlowerSuit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LOVER'S BIRTHDAY", "MOTHER'S DAY", "WEDDING PARTY" }));
        jCBFlowerSuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBFlowerSuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFlowerName)
                    .addComponent(jTextFlowerColour)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCBFlowerSuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFlowerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFlowerColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCBFlowerSuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        EDIT.setText("EDIT");
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });

        SEARCH.setText("SEARCH");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADD)
                    .addComponent(DELETE)
                    .addComponent(EDIT)
                    .addComponent(SEARCH))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFlowerColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFlowerColourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFlowerColourActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here:
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Delete this data", "Delete", dialogButton);
        if(dialogResult == 0){
            dtm.removeRow(row);
            flowerslist.remove(row);
            dtm.setRowCount(0);
             for (int i=0; i<flowerslist.size(); i++){
                Object[]objs = {flowerslist.get(i).flowername,flowerslist.get(i).flowercolour,flowerslist.get(i).flowersuit};
                dtm.addRow(objs);
            }
            clearField();
        }else{
        
        }
    }//GEN-LAST:event_DELETEActionPerformed
    
    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        // TODO add your handling code here:
        String flowername = jTextFlowerName.getText();
        String flowercolour = jTextFlowerColour.getText();
        String flowersuit = jCBFlowerSuit.getSelectedItem().toString();
        flowerslist.add(new Flowers(flowername,flowercolour,flowersuit));
        dtm.setRowCount(0);//reset data model
        for (int i=0; i<flowerslist.size(); i++){
            Object[]objs = {flowerslist.get(i).flowername,flowerslist.get(i).flowercolour,flowerslist.get(i).flowersuit};
            dtm.addRow(objs);
        }
        //reset
        clearField();
    }//GEN-LAST:event_ADDActionPerformed
    
    private void clearField(){
        jTextFlowerName.requestFocus();
        jTextFlowerName.setText("");
        jTextFlowerColour.setText("");
        jCBFlowerSuit.setSelectedIndex(0);
    }
    
    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed
        // TODO add your handling code here:
        String editedflowername = jTextFlowerName.getText();
        String editedflowercolour = jTextFlowerColour.getText();
        String editedflowersuit = jCBFlowerSuit.getSelectedItem().toString();
        
       flowerslist.get(row).flowername = editedflowername;
       flowerslist.get(row).flowercolour= editedflowercolour;
       flowerslist.get(row).flowersuit = editedflowersuit;
       dtm.setRowCount(0);
       
       for (int i=0; i<flowerslist.size(); i++){
            Object[]objs = {flowerslist.get(i).flowername,flowerslist.get(i).flowercolour,flowerslist.get(i).flowersuit};
            dtm.addRow(objs);
       }
    }//GEN-LAST:event_EDITActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Search Flower Name : ");
        for (int i=0; i<flowerslist.size(); i++){
            if(flowerslist.get(i).flowername.equalsIgnoreCase(input)){
            JOptionPane.showMessageDialog(SEARCH, "Found!!!", "Search flower", 2);
            jTextFlowerName.setText(flowerslist.get(i).flowername);
            jTextFlowerColour.setText(flowerslist.get(i).flowercolour);
            String flowersuit = flowerslist.get(i).flowersuit;
                return;
                    }
                }
                    
    JOptionPane.showMessageDialog(SEARCH, "Not Found!!!", "Search Flower", 2 );
    }//GEN-LAST:event_SEARCHActionPerformed
    
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        row = jTable2.getSelectedRow();
        col = jTable2.getColumnCount();
        System.out.println(row+","+col);
        
        jTextFlowerName.setText(dtm.getValueAt(row, 0).toString());
        jTextFlowerColour.setText(dtm.getValueAt(row, 1).toString());
        String flowersuit = (dtm.getValueAt(row, 2).toString());
        
        for (int i=0; i<(jCBFlowerSuit.getItemCount()); i++){
            if (jCBFlowerSuit.getItemAt(i).equalsIgnoreCase(flowersuit)){
                jCBFlowerSuit.setSelectedIndex(i);
            }
        }    
    }//GEN-LAST:event_jTable2MouseClicked

    private void jCBFlowerSuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBFlowerSuitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBFlowerSuitActionPerformed

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlowersList().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton DELETE;
    private javax.swing.JButton EDIT;
    private javax.swing.JButton SEARCH;
    private javax.swing.JComboBox<String> jCBFlowerSuit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFlowerColour;
    private javax.swing.JTextField jTextFlowerName;
    // End of variables declaration//GEN-END:variables

}


